// Mocks generated by Mockito 5.4.4 from annotations
// in lakuemas/test/features/profile/data/repositories/address_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:lakuemas/cores/models/base_list_resp.dart' as _i2;
import 'package:lakuemas/cores/models/base_resp.dart' as _i3;
import 'package:lakuemas/cores/services/local_data_source/i_token_local_data_source.dart'
    as _i4;
import 'package:lakuemas/features/profile/data/data_sources/interfaces/i_address_remote_data_source.dart'
    as _i6;
import 'package:lakuemas/features/profile/data/models/address_req.dart' as _i8;
import 'package:lakuemas/features/profile/data/models/country_model.dart'
    as _i7;
import 'package:lakuemas/features/profile/data/models/detail_district_model.dart'
    as _i12;
import 'package:lakuemas/features/profile/data/models/get_city_model.dart'
    as _i10;
import 'package:lakuemas/features/profile/data/models/get_district_model.dart'
    as _i11;
import 'package:lakuemas/features/profile/data/models/get_province_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseListResp_0<T> extends _i1.SmartFake
    implements _i2.BaseListResp<T> {
  _FakeBaseListResp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResp_1<T> extends _i1.SmartFake implements _i3.BaseResp<T> {
  _FakeBaseResp_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITokenLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITokenLocalDataSource extends _i1.Mock
    implements _i4.ITokenLocalDataSource {
  MockITokenLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveAccessToken(String? accToken) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessToken,
          [accToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [refreshToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [IAddressRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAddressRemoteDataSource extends _i1.Mock
    implements _i6.IAddressRemoteDataSource {
  @override
  _i5.Future<_i2.BaseListResp<_i7.CountryModel>> getCountries({
    String? accessToken,
    String? refreshToken,
    _i8.AddressReq? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCountries,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #request: request,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i7.CountryModel>>.value(
            _FakeBaseListResp_0<_i7.CountryModel>(
          this,
          Invocation.method(
            #getCountries,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.BaseListResp<_i7.CountryModel>>.value(
                _FakeBaseListResp_0<_i7.CountryModel>(
          this,
          Invocation.method(
            #getCountries,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i7.CountryModel>>);

  @override
  _i5.Future<_i2.BaseListResp<_i9.GetProvinceModel>> getProvinces({
    String? accessToken,
    String? refreshToken,
    _i8.AddressReq? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProvinces,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #request: request,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i9.GetProvinceModel>>.value(
            _FakeBaseListResp_0<_i9.GetProvinceModel>(
          this,
          Invocation.method(
            #getProvinces,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.BaseListResp<_i9.GetProvinceModel>>.value(
                _FakeBaseListResp_0<_i9.GetProvinceModel>(
          this,
          Invocation.method(
            #getProvinces,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i9.GetProvinceModel>>);

  @override
  _i5.Future<_i2.BaseListResp<_i10.GetCityModel>> getCities({
    String? accessToken,
    String? refreshToken,
    _i8.AddressReq? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCities,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #request: request,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i10.GetCityModel>>.value(
            _FakeBaseListResp_0<_i10.GetCityModel>(
          this,
          Invocation.method(
            #getCities,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.BaseListResp<_i10.GetCityModel>>.value(
                _FakeBaseListResp_0<_i10.GetCityModel>(
          this,
          Invocation.method(
            #getCities,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i10.GetCityModel>>);

  @override
  _i5.Future<_i2.BaseListResp<_i11.GetDistrictModel>> getDistricts({
    String? accessToken,
    String? refreshToken,
    _i8.AddressReq? request,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDistricts,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #request: request,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i11.GetDistrictModel>>.value(
            _FakeBaseListResp_0<_i11.GetDistrictModel>(
          this,
          Invocation.method(
            #getDistricts,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.BaseListResp<_i11.GetDistrictModel>>.value(
                _FakeBaseListResp_0<_i11.GetDistrictModel>(
          this,
          Invocation.method(
            #getDistricts,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #request: request,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i11.GetDistrictModel>>);

  @override
  _i5.Future<_i3.BaseResp<_i12.DetailDistrictModel>> getDetailDistrict({
    String? accessToken,
    String? refreshToken,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailDistrict,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #id: id,
          },
        ),
        returnValue: _i5.Future<_i3.BaseResp<_i12.DetailDistrictModel>>.value(
            _FakeBaseResp_1<_i12.DetailDistrictModel>(
          this,
          Invocation.method(
            #getDetailDistrict,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #id: id,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.BaseResp<_i12.DetailDistrictModel>>.value(
                _FakeBaseResp_1<_i12.DetailDistrictModel>(
          this,
          Invocation.method(
            #getDetailDistrict,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #id: id,
            },
          ),
        )),
      ) as _i5.Future<_i3.BaseResp<_i12.DetailDistrictModel>>);
}
