// Mocks generated by Mockito 5.4.4 from annotations
// in lakuemas/test/features/beranda/data/repositories/beranda_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:lakuemas/cores/models/base_list_resp.dart' as _i2;
import 'package:lakuemas/cores/models/base_resp.dart' as _i3;
import 'package:lakuemas/cores/services/local_data_source/i_token_local_data_source.dart'
    as _i4;
import 'package:lakuemas/features/_core/transaction/data/models/price_model.dart'
    as _i10;
import 'package:lakuemas/features/_core/user/data/models/balance_model.dart'
    as _i7;
import 'package:lakuemas/features/article/data/models/article_model.dart'
    as _i9;
import 'package:lakuemas/features/beranda/data/data_sources/interfaces/i_beranda_remote_data_source.dart'
    as _i6;
import 'package:lakuemas/features/beranda/data/models/menu_model.dart' as _i8;
import 'package:lakuemas/features/beranda/data/models/promo_model.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseListResp_0<T> extends _i1.SmartFake
    implements _i2.BaseListResp<T> {
  _FakeBaseListResp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseResp_1<T> extends _i1.SmartFake implements _i3.BaseResp<T> {
  _FakeBaseResp_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITokenLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITokenLocalDataSource extends _i1.Mock
    implements _i4.ITokenLocalDataSource {
  MockITokenLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveAccessToken(String? accToken) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessToken,
          [accToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [refreshToken],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [IBerandaRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBerandaRemoteDataSource extends _i1.Mock
    implements _i6.IBerandaRemoteDataSource {
  MockIBerandaRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BaseListResp<_i7.BalanceModel>> getBalances({
    String? accessToken,
    String? refreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalances,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i7.BalanceModel>>.value(
            _FakeBaseListResp_0<_i7.BalanceModel>(
          this,
          Invocation.method(
            #getBalances,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i7.BalanceModel>>);

  @override
  _i5.Future<_i2.BaseListResp<_i8.MenuModel>> getMenus({
    String? accessToken,
    String? refreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenus,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i8.MenuModel>>.value(
            _FakeBaseListResp_0<_i8.MenuModel>(
          this,
          Invocation.method(
            #getMenus,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i8.MenuModel>>);

  @override
  _i5.Future<_i2.BaseListResp<_i9.ArticleModel>> getArticles({
    String? accessToken,
    String? refreshToken,
    String? limit,
    String? page,
    String? orderBy,
    String? sortBy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArticles,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #limit: limit,
            #page: page,
            #orderBy: orderBy,
            #sortBy: sortBy,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i9.ArticleModel>>.value(
            _FakeBaseListResp_0<_i9.ArticleModel>(
          this,
          Invocation.method(
            #getArticles,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #limit: limit,
              #page: page,
              #orderBy: orderBy,
              #sortBy: sortBy,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i9.ArticleModel>>);

  @override
  _i5.Future<_i3.BaseResp<_i10.PriceModel>> getPriceSetting({
    String? accessToken,
    String? refreshToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPriceSetting,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
          },
        ),
        returnValue: _i5.Future<_i3.BaseResp<_i10.PriceModel>>.value(
            _FakeBaseResp_1<_i10.PriceModel>(
          this,
          Invocation.method(
            #getPriceSetting,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.BaseResp<_i10.PriceModel>>);

  @override
  _i5.Future<_i2.BaseListResp<_i11.PromoModel>> getPromos({
    String? accessToken,
    String? refreshToken,
    int? limit,
    int? page,
    String? orderBy,
    String? sortBy,
    String? keyword,
    int? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromos,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #limit: limit,
            #page: page,
            #orderBy: orderBy,
            #sortBy: sortBy,
            #keyword: keyword,
            #isActive: isActive,
          },
        ),
        returnValue: _i5.Future<_i2.BaseListResp<_i11.PromoModel>>.value(
            _FakeBaseListResp_0<_i11.PromoModel>(
          this,
          Invocation.method(
            #getPromos,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #limit: limit,
              #page: page,
              #orderBy: orderBy,
              #sortBy: sortBy,
              #keyword: keyword,
              #isActive: isActive,
            },
          ),
        )),
      ) as _i5.Future<_i2.BaseListResp<_i11.PromoModel>>);

  @override
  _i5.Future<_i3.BaseResp<_i11.PromoModel>> getPromoById({
    String? accessToken,
    String? refreshToken,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPromoById,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #id: id,
          },
        ),
        returnValue: _i5.Future<_i3.BaseResp<_i11.PromoModel>>.value(
            _FakeBaseResp_1<_i11.PromoModel>(
          this,
          Invocation.method(
            #getPromoById,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #id: id,
            },
          ),
        )),
      ) as _i5.Future<_i3.BaseResp<_i11.PromoModel>>);
}
