// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-It3egNliVpTOPOH7W_cqMKdXj4KrvI',
    appId: '1:325480095415:web:451740e50d9b047fd3f732',
    messagingSenderId: '325480095415',
    projectId: 'lakuemas-staging',
    authDomain: 'lakuemas-staging.firebaseapp.com',
    storageBucket: 'lakuemas-staging.appspot.com',
    measurementId: 'G-2N4TFKQF86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb83t7hCtoNq4vv0Vax3As403wa3e4Coo',
    appId: '1:325480095415:android:85d07c456f9893e4d3f732',
    messagingSenderId: '325480095415',
    projectId: 'lakuemas-staging',
    storageBucket: 'lakuemas-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvTjLoAQu00Lv7hMyeYA6kDjZqSQfiuA',
    appId: '1:325480095415:ios:6e5fa139de611f55d3f732',
    messagingSenderId: '325480095415',
    projectId: 'lakuemas-staging',
    storageBucket: 'lakuemas-staging.appspot.com',
    iosBundleId: 'blipcom.Laku-Emas.staging',
  );
}
