// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9iWARJ9_sXwFd4Ri1YZUwpYQhLkjRQCU',
    appId: '1:1070811024002:web:458bf31fd4076b4f19c29b',
    messagingSenderId: '1070811024002',
    projectId: 'lakuemas-notification',
    authDomain: 'lakuemas-notification.firebaseapp.com',
    databaseURL: 'https://lakuemas-notification.firebaseio.com',
    storageBucket: 'lakuemas-notification.appspot.com',
    measurementId: 'G-W0D1HTPXN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7tec3Z6FgdgRQJq9xs0Pux3crakn7ET0',
    appId: '1:1070811024002:android:5c0d84ef269af3a519c29b',
    messagingSenderId: '1070811024002',
    projectId: 'lakuemas-notification',
    databaseURL: 'https://lakuemas-notification.firebaseio.com',
    storageBucket: 'lakuemas-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW8i8T8OjhNaf2WkbyuEHVrsiXSDjl55w',
    appId: '1:1070811024002:ios:572bf2aed465052719c29b',
    messagingSenderId: '1070811024002',
    projectId: 'lakuemas-notification',
    databaseURL: 'https://lakuemas-notification.firebaseio.com',
    storageBucket: 'lakuemas-notification.appspot.com',
    iosBundleId: 'blipcom.Laku-Emas.rev',
  );
}
