// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjw50aqiyQd6HkZOUkJRiYXnvHbHv9JGY',
    appId: '1:713899172299:web:6a91724f2f0004c076964e',
    messagingSenderId: '713899172299',
    projectId: 'lakuemas-dev',
    authDomain: 'lakuemas-dev.firebaseapp.com',
    storageBucket: 'lakuemas-dev.appspot.com',
    measurementId: 'G-YK9JF5NSYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSZ2rUBF5K8CwFT4vLCQsZZHQEkY9UO5Q',
    appId: '1:713899172299:android:801bf584aff5ac1576964e',
    messagingSenderId: '713899172299',
    projectId: 'lakuemas-dev',
    storageBucket: 'lakuemas-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxRaCdqhP5LCxVqihxkxajsYQVKwbXtTM',
    appId: '1:713899172299:ios:5e2ac44d827b032776964e',
    messagingSenderId: '713899172299',
    projectId: 'lakuemas-dev',
    storageBucket: 'lakuemas-dev.appspot.com',
    iosBundleId: 'blipcom.Laku-Emas.dev',
  );
}
