// Mocks generated by Mockito 5.4.4 from annotations
// in lakuemas/test/features/transfer/data/respositories/transfer_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lakuemas/cores/models/base_resp.dart' as _i2;
import 'package:lakuemas/cores/services/local_data_source/i_token_local_data_source.dart'
    as _i3;
import 'package:lakuemas/features/_core/user/data/models/user_data_model.dart'
    as _i9;
import 'package:lakuemas/features/transfer/data/data_sources/interfaces/i_transfer_local_data_source.dart'
    as _i8;
import 'package:lakuemas/features/transfer/data/data_sources/interfaces/i_transfer_remote_data_source.dart'
    as _i5;
import 'package:lakuemas/features/transfer/data/models/transfer_charge_model.dart'
    as _i6;
import 'package:lakuemas/features/transfer/data/models/transfer_checkout_model.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResp_0<T> extends _i1.SmartFake implements _i2.BaseResp<T> {
  _FakeBaseResp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITokenLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITokenLocalDataSource extends _i1.Mock
    implements _i3.ITokenLocalDataSource {
  MockITokenLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveAccessToken(String? accToken) => (super.noSuchMethod(
        Invocation.method(
          #saveAccessToken,
          [accToken],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveRefreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRefreshToken,
          [refreshToken],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [ITransferRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransferRemoteDataSource extends _i1.Mock
    implements _i5.ITransferRemoteDataSource {
  MockITransferRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResp<_i6.TransferChargeModel>> transferCharge({
    String? accessToken,
    String? refreshToken,
    required bool? isAddFavorite,
    required double? goldWeight,
    required String? accountNumber,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferCharge,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #isAddFavorite: isAddFavorite,
            #goldWeight: goldWeight,
            #accountNumber: accountNumber,
            #note: note,
          },
        ),
        returnValue: _i4.Future<_i2.BaseResp<_i6.TransferChargeModel>>.value(
            _FakeBaseResp_0<_i6.TransferChargeModel>(
          this,
          Invocation.method(
            #transferCharge,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #isAddFavorite: isAddFavorite,
              #goldWeight: goldWeight,
              #accountNumber: accountNumber,
              #note: note,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResp<_i6.TransferChargeModel>>);

  @override
  _i4.Future<_i2.BaseResp<_i7.TransferCheckoutModel>> transferCheckout({
    String? accessToken,
    String? refreshToken,
    required String? transactionKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferCheckout,
          [],
          {
            #accessToken: accessToken,
            #refreshToken: refreshToken,
            #transactionKey: transactionKey,
          },
        ),
        returnValue: _i4.Future<_i2.BaseResp<_i7.TransferCheckoutModel>>.value(
            _FakeBaseResp_0<_i7.TransferCheckoutModel>(
          this,
          Invocation.method(
            #transferCheckout,
            [],
            {
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #transactionKey: transactionKey,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseResp<_i7.TransferCheckoutModel>>);
}

/// A class which mocks [ITransferLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransferLocalDataSource extends _i1.Mock
    implements _i8.ITransferLocalDataSource {
  MockITransferLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.UserDataModel?> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i4.Future<_i9.UserDataModel?>.value(),
      ) as _i4.Future<_i9.UserDataModel?>);
}
