// Mocks generated by Mockito 5.4.4 from annotations
// in lakuemas/test/features/laku_save/domain/usecases/get_about_uc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:lakuemas/cores/errors/app_failure.dart' as _i5;
import 'package:lakuemas/features/laku_save/data/models/get_transactions_req.dart'
    as _i9;
import 'package:lakuemas/features/laku_save/data/models/lakusave_checkout_req.dart'
    as _i7;
import 'package:lakuemas/features/laku_save/domain/entities/gold_deposit_entity.dart'
    as _i6;
import 'package:lakuemas/features/laku_save/domain/entities/transaction_entity.dart'
    as _i8;
import 'package:lakuemas/features/laku_save/domain/repositories/i_lakusave_repoisitory.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILakusaveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockILakusaveRepository extends _i1.Mock
    implements _i3.ILakusaveRepository {
  MockILakusaveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, _i6.GoldDepositEntity>>
      getMasterData() => (super.noSuchMethod(
            Invocation.method(
              #getMasterData,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.AppFailure, _i6.GoldDepositEntity>>.value(
                _FakeEither_0<_i5.AppFailure, _i6.GoldDepositEntity>(
              this,
              Invocation.method(
                #getMasterData,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.AppFailure, _i6.GoldDepositEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, bool>> checkout(
          {required _i7.LakusaveCheckoutReq? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkout,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, bool>>.value(
            _FakeEither_0<_i5.AppFailure, bool>(
          this,
          Invocation.method(
            #checkout,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, bool>> cancel(
          {String? transactionCode}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {#transactionCode: transactionCode},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, bool>>.value(
            _FakeEither_0<_i5.AppFailure, bool>(
          this,
          Invocation.method(
            #cancel,
            [],
            {#transactionCode: transactionCode},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, bool>>);

  @override
  _i4.Future<
      _i2.Either<_i5.AppFailure, List<_i8.TransactionEntity>>> getTransactions(
          {required _i9.GetTransactionsReq? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.AppFailure, List<_i8.TransactionEntity>>>.value(
            _FakeEither_0<_i5.AppFailure, List<_i8.TransactionEntity>>(
          this,
          Invocation.method(
            #getTransactions,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, List<_i8.TransactionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, bool>> updateExtend({
    int? extendId,
    String? accountNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExtend,
          [],
          {
            #extendId: extendId,
            #accountNumber: accountNumber,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, bool>>.value(
            _FakeEither_0<_i5.AppFailure, bool>(
          this,
          Invocation.method(
            #updateExtend,
            [],
            {
              #extendId: extendId,
              #accountNumber: accountNumber,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.AppFailure, String?>> getAbout() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAbout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AppFailure, String?>>.value(
            _FakeEither_0<_i5.AppFailure, String?>(
          this,
          Invocation.method(
            #getAbout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AppFailure, String?>>);
}
